fix(SpokePool): Apply exclusivity consistently
across-protocol/contracts pull request #649
Opened 2024-10-09 22:00 UTC by pxrl

The new relative exclusivity check has not been propagated to fillV3RelayWithUpdatedDeposit(). Identified via test case failures in the relayer.

This is a very-low criticality issue. It's very unlikely that any relayer would be trying to call `fillV3RelayWithUpdatedDeposit()` within the exclusivity window.

2024-10-09 22:15 UTC, pxrl commented on contracts/SpokePool.sol
>          }
We now have this check in 3 places; worth factoring out to a function?

2024-10-09 22:15 UTC, pxrl commented on contracts/SpokePool.sol
> +            relayData.exclusiveRelayer != msg.sender &&
```suggestion
```

2024-10-09 22:40 UTC, nicholaspai approved these changes
Dang good catch. I think refactoring to shared internal function could make sense

2024-10-10 02:28 UTC, nicholaspai requested changes
Can you add unit tests to these functions similar to these so we can prevent regressions? https://github.com/across-protocol/contracts/blob/master/test/evm/hardhat/SpokePool.Relay.ts#L330

2024-10-11 13:18 UTC, pxrl commented on contracts/SpokePool.sol
>          }
I factored out the common logic to a `_fillIsExclusive()` function. I think this is probably the right call but could be persuaded otherwise.

2024-10-11 13:22 UTC, pxrl commented on contracts/interfaces/V3SpokePoolInterface.sol
> -    error InvalidExclusiveRelayer();
Driveby change - this error is unused. It was dropped with the recent changes to permit relative exclusivity.

2024-10-11 22:40 UTC, pxrl commented
> Can you add unit tests to these functions similar to these so we can prevent regressions? https://github.com/across-protocol/contracts/blob/master/test/evm/hardhat/SpokePool.Relay.ts#L330

Added tests here: https://github.com/across-protocol/contracts/pull/649/commits/6b5f5f9f65a927bb272b59e1a5fe481b22c06742

2024-10-14 14:07 UTC, nicholaspai approved these changes

2024-10-30 13:17 UTC, merged